# Generated by Django 5.2.1 on 2025-07-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_app', '0002_remove_visitorregistration_visit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorregistration',
            name='civil_servant',
            field=models.BooleanField(default=False, help_text='Shaqaale Dowladda miyaad tahay?'),
        ),
    ]
