# Generated by Django 5.2.1 on 2025-07-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_app', '0003_visitorregistration_civil_servant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorregistration',
            name='civil_servant',
            field=models.BooleanField(default=False, help_text='Are you civil servant?'),
        ),
        migrations.AlterField(
            model_name='visitorregistration',
            name='hours_to_stay',
            field=models.DurationField(blank=True, help_text='Enter time like HH:MM', null=True),
        ),
    ]
