# Generated by Django 5.2.1 on 2025-07-16 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_app', '0004_alter_visitorregistration_civil_servant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorregistration',
            name='hours_to_stay',
        ),
    ]
