# Generated by Django 5.2.1 on 2025-07-16 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_app', '0005_remove_visitorregistration_hours_to_stay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorregistration',
            name='check_in_date',
        ),
    ]
