# Generated by Django 5.2.1 on 2025-07-16 12:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_app', '0006_remove_visitorregistration_check_in_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorregistration',
            name='check_in_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitorregistration',
            name='hours_to_stay',
            field=models.DurationField(blank=True, help_text='Enter time like HH:MM', null=True),
        ),
    ]
